config/routes.rb
Haha5pig::Application.routes.draw do

      match "users/login"=>"users#login",:as => :login
      match "users/reg"=>"users#reg",:as => :reg
      match "users/logout"=>"users#logout",:as=>:logout
      resources :users
      resources :coms
      resources :breeds
      resources :diseases
      resources :diseasedescs
      resources :matings
      resources :piginfos
      resources :vaccines

  match "users/:id/change" =>"users#change",:as=>:change
end

app/models/breed.rb
class Breed < ActiveRecord::Base
  has_many :piginfo
  
  belongs_to :com
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  # GET /breeds
  # GET /breeds.xml
  def index
    @breeds = Breed.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @breeds }
    end
  end

  # GET /breeds/1
  # GET /breeds/1.xml
  def show
    @breed = Breed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @breed }
    end
  end

  # GET /breeds/new
  # GET /breeds/new.xml
  def new
    @breed = Breed.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @breed }
    end
  end

  # GET /breeds/1/edit
  def edit
    @breed = Breed.find(params[:id])
  end

  # POST /breeds
  # POST /breeds.xml
  def create
    @breed = Breed.new(params[:breed])

    respond_to do |format|
      if @breed.save
        format.html { redirect_to(@breed, :notice => 'Breed was successfully created.') }
        format.xml  { render :xml => @breed, :status => :created, :location => @breed }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @breed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /breeds/1
  # PUT /breeds/1.xml
  def update
    @breed = Breed.find(params[:id])

    respond_to do |format|
      if @breed.update_attributes(params[:breed])
        format.html { redirect_to(@breed, :notice => 'Breed was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @breed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.xml
  def destroy
    @breed = Breed.find(params[:id])
    @breed.destroy

    respond_to do |format|
      format.html { redirect_to(breeds_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/breeds/_form.html.erb
<%= form_for(@breed) do |f| %>
  <% if @breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% @breed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :com_id %><br />
    <%= f.text_field :com_id %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :series %><br />
    <%= f.text_field :series %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing breed</h1>

<%= render 'form' %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

app/views/breeds/index.html.erb
<h1>Listing breeds</h1>

<table>
  <tr>
    <th>Com</th>
    <th>Code</th>
    <th>Name</th>
    <th>Series</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @breeds.each do |breed| %>
  <tr>
    <td><%= breed.com_id %></td>
    <td><%= breed.code %></td>
    <td><%= breed.name %></td>
    <td><%= breed.series %></td>
    <td><%= link_to 'Show', breed %></td>
    <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
    <td><%= link_to 'Destroy', breed, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Breed', new_breed_path %>

app/views/breeds/new.html.erb
<h1>New breed</h1>

<%= render 'form' %>

<%= link_to 'Back', breeds_path %>

app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Com:</b>
  <%= @breed.com_id %>
</p>

<p>
  <b>Code:</b>
  <%= @breed.code %>
</p>

<p>
  <b>Name:</b>
  <%= @breed.name %>
</p>

<p>
  <b>Series:</b>
  <%= @breed.series %>
</p>


<%= link_to 'Edit', edit_breed_path(@breed) %> |
<%= link_to 'Back', breeds_path %>