config/routes.rb
Haha5pig::Application.routes.draw do

      match "users/login"=>"users#login",:as => :login
      match "users/reg"=>"users#reg",:as => :reg
      match "users/logout"=>"users#logout",:as=>:logout
      resources :users
      resources :coms
      resources :breeds
      resources :diseases
      resources :diseasedescs
      resources :matings
      resources :piginfos
      resources :vaccines

  match "users/:id/change" =>"users#change",:as=>:change
end

app/models/user.rb
#encoding: UTF-8

#  @UserTypes = [["trial",2],["vip",1],["admin",0]]


class User < ActiveRecord::Base
  has_many :com
  
  UserTypes = [["试用",2],["vip",1],["管理员",0]]
  States = [["可用",1],["停用",0]] 

  attr_accessor :password_confirmation
  attr_accessor :newpassword,:com_id
  
#validate the contents.
  validates_presence_of :username,:password,:password_confirmation,:level,:starttime,:deadline
 
  validates :username,:length => {:minimum => 5,:maximum => 20,:too_long => "最长不超过20个字符",:too_short=> "最短6个字符"}
  validates :password,:length => {:minimum => 5,:maximum => 20,:too_long => "最长不超过20个字符",:too_short=> "最短6个字符"}
  validates :password_confirmation,:length => {:minimum => 5, :maximum => 20,:too_long => "最长不超过20个字符",:too_short=> "最短6个字符"} 

  validates :username,:uniqueness => {:case_sensitive => false}
  validates :password_confirmation,:presence => true,:if => :same_with_password?
  

private

  def same_with_password?
    :password_confirmation == :password
  end

public
  
  def isAdmin?
    if self.level == nil
      return false
    end
    if self.level.to_i == 0
      return true
    else
      return false
    end
  end

  def isVip? 
    if self.level.to_i == 1
      return true
    else
        return false
    end
  end

  def isTrial?
    if self.level.to_i == 2
      return true
    else
      return false
    end
  end

end

app/controllers/users_controller.rb
#encoding: UTF-8
#
class UsersController < ApplicationController

  load_and_authorize_resource

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    @user.ip = request.remote_ip
    @user.starttime = 0.day.from_now
    @user.deadline = 1.year.from_now
    @user.state = 1 

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user.to_xml }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  # user login page, handler.
  # user should input the username and password
  def login
    if params[:username] !=nil && params[:password] != nil
      #find the user from db
      @user = User.find_by_username(params[:username])
      if @user !=nil &&  @user.password == params[:password]
        session[:user] = @user
        respond_to do |format|
          logger.info "user:#@user.username logged in"
          flash[:notice] = "登录成功!"
          format.html {redirect_to :action=>"index"}
          format.xml {head :ok}
        end

      elsif @user != nil && @user.password != params[:password]
        respond_to do |format|
          flash[:error] = "用户名密码/错误,请重新登录!"
          format.html {redirect_to :action=>"login"}
        end
      else
        redirect_to login_url 
      end
      #if user inputs the username and  password. 
    else
      flash[:notice] = "请填写用户名/密码."
    end
  end


  def change
    # @user=User.find(params[:id])
    if session[:user] == nil
      @newuser = nil;
      redirect_to :action => :login,:notice =>"请输入用户名和密码："
    else
      @newuser = User.new 
      flash[:notice] = "请输入您的新密码"
      session[:user]
    end
    if params[:user] == nil
      return
    end
    if params[:user][:password] != nil && params[:user][:newpassword]!= nil
      @newuser = session[:user]
      @result=User.find(@newuser.id)
      if params[:user][:password] == @result.password
        @result.password=params[:user][:newpassword]
        session[:user].password = params[:user][:newpassword]
        @result.update_attribute(:password,params[:user][:newpassword])
        flash[:notice] = "密码修改成功"
      else
        flash[:notice] = "原密码错误，请重新输入"
      end
    else
      flash[:error] = "else" 
    end
  end


  # the following action design for loging out the current user.
  # step:1 checking if is there any user status is log in.
  # step:2 if there is a users' status is log in, then get the session of the current user
  # step:3 clear the session. loging out.
  def logout
    if session[:user] != nil
      session[:user]=nil
    end
    flash[:notice]="请先登录"
    redirect_to login_url
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username,"用户名：" %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password,"密码：" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation,"确认密码：" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :level,"用户等级：" %><br />
    <%= f.select :level,User::UserTypes,:prompt=>"选择用户类型" %>. ......试用：2，    付费用户：1，    管理员：0。
  </div>
  <div class="field">
    <%= f.label :ip,"ip地址：" %><br />
    <%= f.text_field :ip ,:readonly => true%>
  </div>
  <div class="field">
    <%= f.label :starttime,"开始时间：" %><br />
    <%= f.date_select :starttime %>
  </div>
  <div class="field">
    <%= f.label :deadline,"截止日期" %><br />
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.select :state,User::States,:default => User::States[0][1] %> 可用：1，  禁用：0
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_functionbar.html.erb

<div id="func_bar">
  <ul>
    <li>
      <%= link_to '补充公司资料', :controller =>'coms', :action=>'create', :id=> @user%>
    </li>
    <li>
      <%= link_to '修改密码', :controller =>'users', :action=>'change', :id=> @user%>
    </li>
  </ul>
</div>
      
      

app/views/users/_login_form.html.erb
<%= form_tag "/users/login", :method=>"post" do %>

  <div class="field">
    <%= label_tag :username,"用户名：" %><br />
    <%= text_field_tag :username %>
  </div>
  <div class="field">
    <%= label_tag :password,"密码：" %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag( "登录") %>
  </div>
<% end %>

app/views/users/change.html.erb
<h1>修改您的用户密码：</h1>



<%= form_tag( { :controller =>'users', :action =>'change'}) do %>
  <div class="field">
    <%= label  :password,"旧密码：" %><br />
    <%= password_field :user,:password%>
  </div>
  <div class="field">
    <%= label :newpassword,"新密码：" %><br />
    <%= password_field :user,:newpassword%>
  </div>
  <div class="actions">
    <%= submit_tag "修改新密码" %>
  </div>
<% end %>

<%= link_to '返回', "/coms" %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/functionbar.html.erb
<div id="func_bar">
  <ul>
    <%= @users.each do |user| %>
    <li>
      <%= link_to 'Create', :controller =>'coms', :action=>'create', :id=> user%>
    </li>
    <li>
      <%= link_to 'Edit', :controller =>'users', :action=>'edit', :id=> user%>
    </li>
  </ul>
</div>
      
      

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Level</th>
    <th>Ip</th>
    <th>Starttime</th>
    <th>Deadline</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.level %></td>
    <td><%= user.ip %></td>
    <td><%= user.starttime %></td>
    <td><%= user.deadline %></td>
    <td><%= user.state %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<h1>登录</h1>

<%= render 'login_form' %>

<%= link_to '注册', reg_url %>

app/views/users/logout.html.erb
<h1>登录</h1>

<%= render 'login_form' %>

<%= link_to '注册', reg_url %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render 'functionbar' %>
<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Level:</b>
  <%= @user.level %>
</p>

<p>
  <b>Ip:</b>
  <%= @user.ip %>
</p>

<p>
  <b>Starttime:</b>
  <%= @user.starttime %>
</p>

<p>
  <b>Deadline:</b>
  <%= @user.deadline %>
</p>

<p>
  <b>State:</b>
  <%= @user.state %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>