config/routes.rb
Haha5pig::Application.routes.draw do

      match "users/login"=>"users#login",:as => :login
      match "users/reg"=>"users#reg",:as => :reg
      match "users/logout"=>"users#logout",:as=>:logout
      resources :users
      resources :coms
      resources :breeds
      resources :diseases
      resources :diseasedescs
      resources :matings
      resources :piginfos
      resources :vaccines

  match "users/:id/change" =>"users#change",:as=>:change
end

app/models/vaccine.rb
class Vaccine < ActiveRecord::Base
  belongs_to :com
end

app/controllers/vaccines_controller.rb
class VaccinesController < ApplicationController
  # GET /vaccines
  # GET /vaccines.xml
  def index
    @vaccines = Vaccine.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vaccines }
    end
  end

  # GET /vaccines/1
  # GET /vaccines/1.xml
  def show
    @vaccine = Vaccine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vaccine }
    end
  end

  # GET /vaccines/new
  # GET /vaccines/new.xml
  def new
    @vaccine = Vaccine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vaccine }
    end
  end

  # GET /vaccines/1/edit
  def edit
    @vaccine = Vaccine.find(params[:id])
  end

  # POST /vaccines
  # POST /vaccines.xml
  def create
    @vaccine = Vaccine.new(params[:vaccine])

    respond_to do |format|
      if @vaccine.save
        format.html { redirect_to(@vaccine, :notice => 'Vaccine was successfully created.') }
        format.xml  { render :xml => @vaccine, :status => :created, :location => @vaccine }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vaccine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vaccines/1
  # PUT /vaccines/1.xml
  def update
    @vaccine = Vaccine.find(params[:id])

    respond_to do |format|
      if @vaccine.update_attributes(params[:vaccine])
        format.html { redirect_to(@vaccine, :notice => 'Vaccine was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vaccine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vaccines/1
  # DELETE /vaccines/1.xml
  def destroy
    @vaccine = Vaccine.find(params[:id])
    @vaccine.destroy

    respond_to do |format|
      format.html { redirect_to(vaccines_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/vaccines_helper.rb
module VaccinesHelper
end

app/views/vaccines/_form.html.erb
<%= form_for(@vaccine) do |f| %>
  <% if @vaccine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vaccine.errors.count, "error") %> prohibited this vaccine from being saved:</h2>

      <ul>
      <% @vaccine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :com_id %><br />
    <%= f.text_field :com_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.date_select :time %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vaccines/edit.html.erb
<h1>Editing vaccine</h1>

<%= render 'form' %>

<%= link_to 'Show', @vaccine %> |
<%= link_to 'Back', vaccines_path %>

app/views/vaccines/index.html.erb
<h1>Listing vaccines</h1>

<table>
  <tr>
    <th>Com</th>
    <th>Name</th>
    <th>Time</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vaccines.each do |vaccine| %>
  <tr>
    <td><%= vaccine.com_id %></td>
    <td><%= vaccine.name %></td>
    <td><%= vaccine.time %></td>
    <td><%= vaccine.desc %></td>
    <td><%= link_to 'Show', vaccine %></td>
    <td><%= link_to 'Edit', edit_vaccine_path(vaccine) %></td>
    <td><%= link_to 'Destroy', vaccine, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vaccine', new_vaccine_path %>

app/views/vaccines/new.html.erb
<h1>New vaccine</h1>

<%= render 'form' %>

<%= link_to 'Back', vaccines_path %>

app/views/vaccines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Com:</b>
  <%= @vaccine.com_id %>
</p>

<p>
  <b>Name:</b>
  <%= @vaccine.name %>
</p>

<p>
  <b>Time:</b>
  <%= @vaccine.time %>
</p>

<p>
  <b>Desc:</b>
  <%= @vaccine.desc %>
</p>


<%= link_to 'Edit', edit_vaccine_path(@vaccine) %> |
<%= link_to 'Back', vaccines_path %>