config/routes.rb
Haha5pig::Application.routes.draw do

      match "users/login"=>"users#login",:as => :login
      match "users/reg"=>"users#reg",:as => :reg
      match "users/logout"=>"users#logout",:as=>:logout
      resources :users
      resources :coms
      resources :breeds
      resources :diseases
      resources :diseasedescs
      resources :matings
      resources :piginfos
      resources :vaccines

  match "users/:id/change" =>"users#change",:as=>:change
end

app/models/diseasedesc.rb
class Diseasedesc < ActiveRecord::Base
  has_many :disease
  
  belongs_to :com
end

app/controllers/diseasedescs_controller.rb
class DiseasedescsController < ApplicationController
  # GET /diseasedescs
  # GET /diseasedescs.xml
  def index
    @diseasedescs = Diseasedesc.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @diseasedescs }
    end
  end

  # GET /diseasedescs/1
  # GET /diseasedescs/1.xml
  def show
    @diseasedesc = Diseasedesc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @diseasedesc }
    end
  end

  # GET /diseasedescs/new
  # GET /diseasedescs/new.xml
  def new
    @diseasedesc = Diseasedesc.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @diseasedesc }
    end
  end

  # GET /diseasedescs/1/edit
  def edit
    @diseasedesc = Diseasedesc.find(params[:id])
  end

  # POST /diseasedescs
  # POST /diseasedescs.xml
  def create
    @diseasedesc = Diseasedesc.new(params[:diseasedesc])

    respond_to do |format|
      if @diseasedesc.save
        format.html { redirect_to(@diseasedesc, :notice => 'Diseasedesc was successfully created.') }
        format.xml  { render :xml => @diseasedesc, :status => :created, :location => @diseasedesc }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @diseasedesc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /diseasedescs/1
  # PUT /diseasedescs/1.xml
  def update
    @diseasedesc = Diseasedesc.find(params[:id])

    respond_to do |format|
      if @diseasedesc.update_attributes(params[:diseasedesc])
        format.html { redirect_to(@diseasedesc, :notice => 'Diseasedesc was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @diseasedesc.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /diseasedescs/1
  # DELETE /diseasedescs/1.xml
  def destroy
    @diseasedesc = Diseasedesc.find(params[:id])
    @diseasedesc.destroy

    respond_to do |format|
      format.html { redirect_to(diseasedescs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/diseasedescs_helper.rb
module DiseasedescsHelper
end

app/views/diseasedescs/_form.html.erb
<%= form_for(@diseasedesc) do |f| %>
  <% if @diseasedesc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diseasedesc.errors.count, "error") %> prohibited this diseasedesc from being saved:</h2>

      <ul>
      <% @diseasedesc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :com_id %><br />
    <%= f.text_field :com_id %>
  </div>
  <div class="field">
    <%= f.label :diseasename %><br />
    <%= f.text_field :diseasename %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diseasedescs/edit.html.erb
<h1>Editing diseasedesc</h1>

<%= render 'form' %>

<%= link_to 'Show', @diseasedesc %> |
<%= link_to 'Back', diseasedescs_path %>

app/views/diseasedescs/index.html.erb
<h1>Listing diseasedescs</h1>

<table>
  <tr>
    <th>Coms</th>
    <th>Diseasename</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diseasedescs.each do |diseasedesc| %>
  <tr>
    <td><%= diseasedesc.coms_id %></td>
    <td><%= diseasedesc.diseasename %></td>
    <td><%= diseasedesc.note %></td>
    <td><%= link_to 'Show', diseasedesc %></td>
    <td><%= link_to 'Edit', edit_diseasedesc_path(diseasedesc) %></td>
    <td><%= link_to 'Destroy', diseasedesc, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diseasedesc', new_diseasedesc_path %>

app/views/diseasedescs/new.html.erb
<h1>New diseasedesc</h1>

<%= render 'form' %>

<%= link_to 'Back', diseasedescs_path %>

app/views/diseasedescs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Coms:</b>
  <%= @diseasedesc.coms_id %>
</p>

<p>
  <b>Diseasename:</b>
  <%= @diseasedesc.diseasename %>
</p>

<p>
  <b>Note:</b>
  <%= @diseasedesc.note %>
</p>


<%= link_to 'Edit', edit_diseasedesc_path(@diseasedesc) %> |
<%= link_to 'Back', diseasedescs_path %>